fragdenstaat_de/theme/templates/footer.html

Piwik changed the name to Matamo and as I see, you already updated piwik to matamo
But some pages should also change the name:

Change Piwik to Matamo

---

Dockerfile

When `docker-compose build` is executed the build failed with the following error message:
```
E: Package 'libgeos-c1' has no installation candidate
```
Replacing `libgeos-c1` with `libgeos-c1v5` solves the problem.

Fix docker-compose build by installing libgeos-c1v5

---

frontend/styles/blog.scss

Das navbar-Dropdown versteckt sich aktuell hinter den Bildern im Blog.

Fix z-index for blog navbar

---

fragdenstaat_de/fds_cms/templates/fds_cms/social_meta.html
fragdenstaat_de/settings/base.py

New proposed default `og:image` with `summary`-style preview (small square image with title and description)
> <img src="https://media.frag-den-staat.de/files/media/main/f9/21/f9211ce7-9924-47da-913f-3070dbd4d298/og-default-sm.png" alt="FragDenStaat logo" width="128">

🚸 swap default share image

---

fragdenstaat_de/fds_blog/tasks.py

Scheduled articles are not indexed on publication. This 'fixes' it. This task should execute every hour.

Add task to index recently published articles

---

fragdenstaat_de/templates/djangocms_frontend/bootstrap5/grid_row.html
fragdenstaat_de/templates/djangocms_frontend/html_container.html
tests/test_misc.py

The templates are basically the same as the upstream ones, but without the `spaceless` tags:
https://github.com/django-cms/djangocms-frontend/blob/master/djangocms_frontend/templates/djangocms_frontend/html_container.html
https://github.com/django-cms/djangocms-frontend/blob/master/djangocms_frontend/contrib/grid/templates/djangocms_frontend/bootstrap5/grid_row.html

🐛 Fix nbsp in spans disappearing

---

fragdenstaat_de/fds_cms/templates/fds_cms/reveal.html

caused by switch to `--bs-` color variables

🩹 fix css variable mismatch with reveal plugin

---

fragdenstaat_de/settings/base.py
fragdenstaat_de/theme/middleware.py

The standard `X-Frame-Options` middleware and the opt-out view decorator `xframe_options_exempt` are not aware of `frame-ancestor` value in our CSP.
Solution here: remove `frame-ancestor` from our standard nginx provided CSP and now set it by default in Django when the `X-Frame-Options` header is sent (ie when the response is not exempt).

Add frame-ancestors CSP value to X-Frame-Options middleware

---

fragdenstaat_de/settings/base.py
fragdenstaat_de/templates/organization/includes/organization_item.html
fragdenstaat_de/templates/organization/organization_list.html
frontend/styles/cms_utils.scss

- 🔧 preserve `.svg` extension for thumbnails
- 💄 move `.partner-logo` class to froide
- 💄 move image classes to froide
- 💄 refine organization pages
:warning: requires okfde/froide#635

organization updates

---

fragdenstaat_de/fds_cms/templates/fds_cms/card/card_image.html
fragdenstaat_de/templates/djangocms_picture/default/picture.html

svg in djangocms_picture currently only works when `Use original image` is enabled

🩹 fix svg images in djangocms-picture and cards

---

fragdenstaat_de/fds_cms/cms_plugins.py
fragdenstaat_de/fds_cms/templates/fds_cms/card/card_image.html
fragdenstaat_de/templates/djangocms_picture/default/picture.html
frontend/styles/cards.scss

- 🩹 add mime type to non-avif source tag too
- ♻️ drop mobile card images, negligible difference
- 💄 adjust wide card images (no more manual image padding)

image improvements

---

frontend/styles/glider.scss

There is no variable name `--bs-bg-body`, according to the docs it's `--bg-body-bg` https://getbootstrap.com/docs/5.3/customize/css-variables/#default

💄 Fix glider background color variable name

---

dev.nix
devsetup.sh

This is a bit of an ugly hack: the devsetup calls some django management
commands that need native libraries (in this case: weasyprint needing
gobject). We set them through DYLD_LIBRARY_PATH, but macOS strips that
when calling devsetup.sh, so we have to set it again inside the devsetup
script.
I'm sure there is a better way to do that, we probably shouldn't be
setting (DY)LD_LIBRARY_PATH in the first place. But I couldn't figure it
out yet.

🩹 Fix devsetup for nix setup

---

fragdenstaat_de/fds_cms/static/js/cms/ckeditor.wysiwyg.js

If it the content starts with a digit, it is prefixed with a dash (which is a valid anchor start).

Make sure id doesn't start with a digit

---

frontend/javascript/vegacharts.js

By default, Altair exports to Vega like this:
```json
"data": {
"name": "data-716699051e44dcc44a893338489d4f65"
},
"datasets": {
"data-716699051e44dcc44a893338489d4f65": [
```
Currently our implementation fails on resolving the data, as it tries to lookup some element with an id that does not exist (as there is no `url` or `data.values`, which is not required though).

🩹 fix data resolution for charts with datasets

---

frontend/javascript/vegacharts.js
frontend/styles/vega.scss

This means style information needs to be removed from spec config key in plugins via e.g.
```python
import json
from fragdenstaat_de.fds_cms.cms_plugins import VegaChartCMSPlugin
charts = VegaChartCMSPlugin.objects.all()
for chart in charts:
vega = json.loads(chart.vega_json)
changed = vega.pop("background", None)
config = vega.get("config")
if config and config.get("axis", {}).get("domainColor"):
vega.pop("config")
changed = True
if changed:
print(chart.title)
print(vega.get("background"), vega.get("config"))
chart.vega_json = json.dumps(vega)
chart.save()
```
Ideally, the chart specs do not come with colour values. This PR makes it so that the spec colours takes precedence over the theme colors, in case you want to adjust per chart.

Make vega charts dark mode compatible

---

fragdenstaat_de/fds_cms/apps.py
fragdenstaat_de/fds_cms/tasks.py

Moves avif generation into a separate task. This might lead to the avif not being there in time for the rendered response – but at least it doesn't hold up the response anymore leading to `SystemExit`.

Generate avif thumbnails async in task

---

fragdenstaat_de/locale/de/LC_MESSAGES/django.po
fragdenstaat_de/theme/management/commands/render_sitemap.py

The sitemap generation takes too much time, so we want to generate them via cronjob and deliver "static" files. (I did not use pythons `tempfile` on purpose as I want to move the sitemap from tmp-Location to the proper location via cron, as currently only Ansible knows about `simple_files` definition.)

Render sitemap

---

fragdenstaat_de/fds_donation/locale/de/LC_MESSAGES/django.po
fragdenstaat_de/settings/base.py
fragdenstaat_de/settings/production.py
fragdenstaat_de/settings/test.py

Elasticsearch requires a scheme otherwise commands like `manage.py search_index --create` will fail with: `ValueError: URL must include a 'scheme', 'host', and 'port' component (ie 'https://localhost:9200')`

Added scheme for elasticsearch URLs in settings

---

fragdenstaat_de/fds_cms/apps.py
fragdenstaat_de/fds_cms/tasks.py

There was a race-condition between the optimization task re-writing the file and the avif task reading it, leading to the avif task seeing only an empty file and crashing

🐛 Run avif generation after thumbnail optimization

---

scripts/create_light_sql.py

`public.document_document` and `document_document` refer to the same table, which lead to the same documents being dumped and inserted twice. This crashed the admin when viewing the document list

🐛 Fix duplicate document entries

---

dev.nix
fragdenstaat_de/fds_donation/tests/README.md
fragdenstaat_de/fds_donation/tests/test_stripe.py
fragdenstaat_de/fds_donation/tests/utils.py
fragdenstaat_de/fds_donation/views.py
fragdenstaat_de/settings/test.py
pytest.ini

- Ensure `stripe` CLI is installed.
- Have the secrets in `PAYMENT_VARIANTS` loaded in `settings/test.py` in your environment
- Run e.g. via `pytest -v --headed -s -m stripe`

Add Playwright tests for Stripe SEPA and CC

---

fragdenstaat_de/templates/_frontend.html

This reverts commit f42b04d4112f8ce49944df4acd1b18f1696d7732.

Revert "Render frontend dependencies via CMS when toolbar present"

---

fragdenstaat_de/settings/base.py

In order to reliably match first instance of closing

Combine closing regexes into one

---

.github/dependabot.yml

dependabot creates corrupt lock file entries for git dependencies. wait until that issue is resolved. see https://github.com/dependabot/dependabot-core/issues/10124

🔧 disable dependabot for frontend deps for now

---

fragdenstaat_de/fds_blog/models.py
fragdenstaat_de/fds_blog/templates/fds_blog/_article_detail.html
fragdenstaat_de/fds_blog/templates/fds_blog/includes/share_article.html
fragdenstaat_de/theme/urls.py

adds share links to the header (only on desktop):
and the footer:

✨ add share links to article page

---

scripts/create_light_sql.py

It seems that postgres need some time after database creation before new commands are accepted.

Fix "the database system is in recovery mode" error

---

fragdenstaat_de/fds_donation/templates/fds_donation/donation_form.html
fragdenstaat_de/templates/foirequest/header/header.html
frontend/styles/main.scss
pnpm-lock.yaml
requirements-dev.txt
requirements-production.txt
requirements.txt

- **🩹 add `.alert-link` to links in alerts**
- **⬆️ upgrade froide**
- **💄 include froide link-styling**

alert links

---

fragdenstaat_de/fds_fximport/askfx.py
fragdenstaat_de/fds_fximport/tasks.py
fragdenstaat_de/fds_fximport/views.py

Previously we ran the importer inside the request handler, which sometimes generated timeout if many / large files were imported or the captcha solving took too long. This PR changes this to only start a task in the request handler which then runs fximport in the background and sends an email to the user on success / failure

Run fximport in background task

---

fragdenstaat_de/fds_donation/services.py
fragdenstaat_de/fds_paperless/views.py
pnpm-lock.yaml
requirements-dev.txt
requirements-production.txt
requirements.txt

Depends on https://github.com/okfde/froide/pull/907

🐛 Use froide is_crew helper

---

fragdenstaat_de/fds_fximport/templates/fds_fximport/import_frag.html
fragdenstaat_de/locale/de/LC_MESSAGES/django.po
fragdenstaat_de/templates/foirequest/body/message/message.html
fragdenstaat_de/theme/templatetags/fds_tags.py

Instead of hiding the Frontex import button after a message has been imported, we now disable it and show a tooltip explaining why. This improves UX by:
- Making the button's state more visible to users
- Providing clear feedback about why the action is not available
Changes:
- Add is_frontex_imported template filter
- Update import button to show disabled state with tooltip
- Pass import status to template
- Clean up template code and translations
closes fragdenstaat/issues#17

🔧 Disable Frontex import button instead of hiding it

---

fragdenstaat_de/fds_paperless/paperless.py
fragdenstaat_de/fds_paperless/urls.py
fragdenstaat_de/fds_paperless/views.py

- **⚰️ remove unneeded paperless views**
- **🩹 don't cache pdf, leads to confusion when editing in paperless**
- **🐛 fix request field not being applied properly**

paperless fixes

---

fragdenstaat_de/fds_paperless/views.py
fragdenstaat_de/settings/base.py

previously, only crew members could be recipients of paperless imports

✨ add paperless recipient group to specify additional users

---

fragdenstaat_de/fds_blog/templates/fds_blog/includes/blog_picture_small.html
fragdenstaat_de/fds_cms/cms_plugins.py
fragdenstaat_de/fds_cms/templates/cms/plugins/primarylink/_picture.html
fragdenstaat_de/fds_cms/templates/cms/plugins/primarylink/tile.html
fragdenstaat_de/fds_cms/templates/fds_cms/external_pixel.html
fragdenstaat_de/templates/datashow/base.html
fragdenstaat_de/templates/djangocms_picture/email/picture.html
fragdenstaat_de/templates/djangocms_picture/hero/picture.html
fragdenstaat_de/templates/djangocms_video/default/_embed_thumbnail.html
fragdenstaat_de/templates/djangocms_video/default/video_player.html
fragdenstaat_de/theme/templatetags/video_player_tags.py
frontend/javascript/consentbanner.ts
pyproject.toml

- video embeds now need user consent
- refactored consentbanner, dropped upstream component. see https://github.com/django-commons/django-cookie-consent/issues/155
- no longer passing cookie status as json data in html, using api request instead. this should allow for better caching.

✨ add consent banner for video embeds

---

fragdenstaat_de/settings/production.py

The current logging setup produces **duplicate log records**. This happens because individual loggers are configured with both `"propagate": True` and explicit `"handlers": ["console"]`.
Example:
```python
LOGGING = {
"loggers": {
"": {"handlers": ["console"], "level": "WARNING"},
"froide": {"level": "INFO", "propagate": True, "handlers": ["console"]},
"fragdenstaat_de": {
"level": "INFO",
"propagate": True,
"handlers": ["console"],
},
...
}
}
```
According to the [Python logging docs](https://docs.python.org/3/library/logging.html#logger-objects) (see the infobox on `propagate`), using both leads to duplicate output:
> If you attach a handler to a logger and one or more of its ancestors, it may emit the same record multiple times. In general, you should not need to attach a handler to …

🔊 Simplify logging config to avoid duplicate log records
