fragdenstaat_de/theme/templates/base.html
=> Delete correctiv text

fragdenstaat_de/theme/templates/footer.html
I guess the video needs to be added to the playlist as well.
=> Link to latest FragDenStaat talk on YouTube

fragdenstaat_de/theme/locale/de/LC_MESSAGES/django.po
"Ihre Password wurde gesetzt" >> "Ihr Passwort wurde gesetzt"
=> Fixed typo

fragdenstaat_de/fds_donation/cms_plugins.py, fragdenstaat_de/fds_donation/templates/fds_donation/cms_plugins/donation_progress_bar.html
zu meiner Verteidigung: https://www.python.org/dev/peps/pep-0378/#main-proposal-from-nick-coghlan-originally-called-proposal-i
=> Enable German number display

devsetup.sh, webpack.config.js
https://github.com/okfde/froide-exam/pull/1 added frontend styles and scripts. This PR adds them to the webpack config.
=> Include froide-exam in webpack build

fragdenstaat_de/fds_newsletter/templatetags/newsletter_tags.py, fragdenstaat_de/templates/foirequest/sent.html
See reference Figma: https://www.figma.com/file/E1b5GfyjdOzlpSjAR6eov0/Anfrage-versendet?node-id=0%3A1 and okfde/froide#421
=> Request sent page

fragdenstaat_de/templates/foirequest/alpha/header/header.html, fragdenstaat_de/templates/foirequest/show.html
see https://forum.okfn.de/c/fragdenstaat/sachsen-transparenzgesetz-voranbringen/12
=> add banner for transparenzgesetz sachsen forum

devsetup.sh
Since we already install pre-commit in our the devsetup-script, why not activate it as well?
=> 🧑‍💻 Automatically install pre-commit hook if repo has a config

fragdenstaat_de/templates/organization/includes/organization_item.html, fragdenstaat_de/templates/organization/includes/user_card.html, fragdenstaat_de/templates/organization/organization_detail.html, fragdenstaat_de/templates/organization/organization_list.html
This PR adds FdS-style theming for https://github.com/okfde/froide/pull/593, similar to our own team page
=> 💄 Add custom theme for organization pages

fragdenstaat_de/fds_ogimage/templates/fds_ogimage/foirequest.html, fragdenstaat_de/theme/management/commands/calculate_stats.py
Needs to be merged / deployed together with https://github.com/okfde/froide/pull/614
=> ♻️ Use FoiRequest.created_at instead of first_message

fragdenstaat_de/fds_blog/locale/de/LC_MESSAGES/django.po, fragdenstaat_de/fds_cms/cms_plugins.py, fragdenstaat_de/fds_cms/locale/de/LC_MESSAGES/django.po, fragdenstaat_de/fds_donation/locale/de/LC_MESSAGES/django.po, fragdenstaat_de/locale/de/LC_MESSAGES/django.po, fragdenstaat_de/theme/locale/de/LC_MESSAGES/django.po
- 🌐 use translated text for continue link
- 💬 update translations
=> translate continue button

.github/workflows/ci.yml
=> 💚 Use python3-dev instead of python-dev for CI

fragdenstaat_de/templates/froide_legalaction/legaldecision_detail.html
requires okfde/django-filingcabinet#30
=> 🩹 use pdf viewer template tag instead of iframe

fragdenstaat_de/theme/amenity_updater.py, fragdenstaat_de/theme/tasks.py
For updating OSM data in django-amenities for the campaigns on Topf Secret and Energieausweis.
=> Add amenity updater task

.github/workflows/ci.yml
- 👷 fix pip caching in ci, bump `setup-python`
- 👷 bump `actions/checkout`
=> fix pip caching in ci & bump actions

fragdenstaat_de/templates/djangocms_picture/hero/picture.html, frontend/styles/cms_elements.scss
This reverts commit 675d25c780eaff3720124f90e26ef238c0b44dcf.
=> ⏪ revert "Use img tag for hero image instead of background"

fragdenstaat_de/fds_blog/templates/fds_blog/blog_preview.html, fragdenstaat_de/fds_blog/templatetags/blog_tags.py, fragdenstaat_de/templates/error_base.html
image is stored in filer, maybe there's a better way?
=> 🚧 error page redesign

fragdenstaat_de/settings/production.py
To allow mails from testservers we need to be able to configure FROM headers.
=> Use ENV variables for FROM in mails

frontend/styles/header.scss
- 🐛 fix navbar being hidden behind sticky/fixed elements
- 💄 adjust mobile link colors
=> navbar touchups

scripts/create_light_sql.py, scripts/safe_fks.txt
Previously the FK from FoiRequest to FoiProject made it that only requests which have a project were dumped. However we also want requests without a project to be dumped"
=> 🐛 Add safe fks to light dump script

fragdenstaat_de/fds_donation/templates/fds_donation/forms/widgets/amount_input.html, frontend/javascript/donation-form.ts
changes:
- show required asterisk for address field, when address is expanded
- use bootstrap collapse
- use `active` classes instead of switching between `btn-primary` and `btn-outline-primary`
- highlight "other amount" button when other amount is entered
- refactor code: still a lot of boilerplate, maybe make this a Vue component in the future
=> 💄 add required indicator to address fields

frontend/styles/blog.scss
It uses text-container class and should not define its own column
=> Fix infotextbox column styling

frontend/styles/main.scss
=> Remove color-contrast SCSS module

fragdenstaat_de/settings/base.py, fragdenstaat_de/theme/legal_backup.py, requirements-production.in, requirements-production.txt
Only merge when WebDAV location is finalised and old files have been moved.
=> Move legal backup to use webdav

fragdenstaat_de/fds_blog/cms_plugins.py, fragdenstaat_de/fds_blog/templates/fds_blog/includes/blog_item_featured_top.html, fragdenstaat_de/fds_blog/templates/fds_blog/plugins/blog_container.html
- **✨ add Blog Container plugin; matches text width**
- **💄 full opacity background on top featured article**
=> further blog touchups

fragdenstaat_de/fds_cms/cms_apps.py, fragdenstaat_de/fds_cms/urls_plainapi.py, fragdenstaat_de/fds_cms/views.py
It renders the content placeholder of the pages on the same tree without templates
=> Add plain API CMS app

fragdenstaat_de/fds_blog/admin.py, fragdenstaat_de/fds_blog/templates/fds_blog/_article_detail.html, fragdenstaat_de/fds_blog/templates/fds_blog/includes/_authors.html, frontend/styles/blog.scss
- **🩹 remove space before comma in author list**
- **💄 fix weird word breaking/spacing in author list on some screens**
- **✨ add admin action to set blog category donation banner**
- **♻️ only show donation banner when explicitly provided**
=> more blog touchups

package.json, pnpm-lock.yaml, pyproject.toml, requirements-dev.txt, requirements-production.txt, requirements.txt
- **🐛 use requirements.txt in translation ci**
- **➖ remove django-oauth-toolkit (already included in froide), bump deps**
=> fix version clash

pnpm-lock.yaml, pyproject.toml, requirements-dev.txt, requirements-production.txt, requirements.txt
- **➖ remove stripe, use version from froide_payment**
- **📌 pin channels and channels_redis, bump deps**
- **🚑 temporarily add async-timeout as redis error workaround**
=> tooling fixes

frontend/javascript/misc/shuffle-items.ts
=> 🩹 don't shuffle items in cms edit mode

fragdenstaat_de/fds_blog/models.py, fragdenstaat_de/fds_blog/templates/fds_blog/content/_article_video_header.html, fragdenstaat_de/fds_blog/templates/fds_blog/placeholders.html, fragdenstaat_de/fds_blog/views.py, fragdenstaat_de/settings/base.py, frontend/styles/blog.scss, frontend/styles/header.scss, pnpm-lock.yaml, requirements-dev.txt, requirements-production.txt, requirements.txt
- Adds new placeholder 'header' that can contain plugins.
- Adds new article content template that removes article image and instead sets a video behind article header/teaser.
=> Add basic video header for articles

frontend/styles/blog.scss, pnpm-lock.yaml, requirements-dev.txt, requirements-production.txt, requirements.txt
- **💄 touch-up video header issues**
- **⬆️ update froide**
=> 💄 touch-up video header issues

fragdenstaat_de/settings/base.py, pnpm-lock.yaml, requirements-dev.txt, requirements-production.txt, requirements.txt, vite.config.js
- **add postupload.js**
- **set proper online help path/link**
- **⬆️ update froide**
=> postupload

pyproject.toml, requirements-dev.txt, requirements-production.txt, requirements.txt
https://github.com/carltongibson/django-filter/issues/1689
=> 🐛 Pin django-filter<24.1

devsetup.sh, fragdenstaat_de/settings/base.py, pyproject.toml, requirements-dev.txt, requirements-production.txt, requirements.txt
- **➕ Add froide-evidencecollection to installed apps**
- **➕ Require gsheets-extra for froide-evidencecollection**
- **🧑‍💻 Add evcoll to devsetup repos**
- **⬆️ Bump evcoll version**
=> Add froide-evidencecollection

fragdenstaat_de/fds_paperless/filters.py, fragdenstaat_de/fds_paperless/forms.py, fragdenstaat_de/fds_paperless/paperless.py, fragdenstaat_de/fds_paperless/templates/fds_paperless/add_postal_message.html, fragdenstaat_de/fds_paperless/templates/fds_paperless/list_documents.html, fragdenstaat_de/fds_paperless/templates/fds_paperless/select_request.html, fragdenstaat_de/fds_paperless/urls.py, fragdenstaat_de/fds_paperless/views.py, fragdenstaat_de/settings/base.py, pnpm-lock.yaml, requirements-dev.txt, requirements-production.txt, requirements.txt
new flow:
1. pick the document(s) you want to import
2. search for the corresponding request, which is made easy with filters (i.e. user, public body)
3. add the document to the request like usual
requires corresponding froide branch
=> ✨ improve paperless document import

.github/dependabot.yml
=> 🔧 re-activate dependapot for npm updates

fragdenstaat_de/fds_newsletter/forms.py
- **💬 newsletter import: add description for csv format**
- **🥅 newsletter import: show error message when no email template is found**
=> fixes for newsletter import

fragdenstaat_de/fds_events/cms_plugins.py, fragdenstaat_de/fds_events/templates/fds_events/event_detail.html, fragdenstaat_de/fds_events/views.py
- **🌐 add context markers to "event" strings**
- **💄 fix breadcrumbs**
=> event app fixes

frontend/styles/homepage.scss
- **💄 simplify testimonial, respect dark mode**
- **💄 prepare for new home page**
=> homepage css

fragdenstaat_de/settings/base.py, frontend/styles/main.scss, pnpm-lock.yaml, requirements-dev.txt, requirements-production.txt, requirements.txt
companion to https://github.com/okfde/froide/pull/960
=> New Attachment Manager

fragdenstaat_de/fds_cms/contact.py, fragdenstaat_de/fds_donation/export.py, fragdenstaat_de/fds_fximport/askfx.py, fragdenstaat_de/fds_fximport/data.py, fragdenstaat_de/fds_fximport/helper.py
- Move specialized third party modules out of initial import path
- Restructure `fds_fximport` to separate data types from logic, short-circuit one check and delay import
=> Improve initial import time of project

fragdenstaat_de/templates/cmssites/cmssite/gegenrechtsschutz.html, frontend/javascript/gegenrechtsschutz.ts, frontend/styles/base.scss, frontend/styles/gegenrechtsschutz.scss, frontend/styles/main.scss, frontend/styles/variables.scss, package.json, pnpm-lock.yaml, vite.config.ts
The structure is still a bit difficult to understand between froide/fds and now this (where are SASS vars defined, overwritten, where are sass maps defined, where do they become CSS properties – or not).
This would create a second main CSS entrypoint with changed primary and secondary color. Is it worth it?
=> Add GRS styles

fragdenstaat_de/settings/base.py, fragdenstaat_de/templates/scannerapp/postupload.html, frontend/styles/misc.scss, pnpm-lock.yaml, requirements-dev.txt, requirements-production.txt, requirements.txt
companion to https://github.com/okfde/froide/pull/1046
=> postupload desktop files

pnpm-lock.yaml, requirements-dev.txt, requirements-production.txt, requirements.txt
for https://github.com/okfde/froide/pull/1068
=> postupload preview timing

fragdenstaat_de/fds_blog/templates/fds_blog/includes/_authors.html
Fixes https://github.com/fragdenstaat/issues/issues/168
=> 💄 Remove space before commas following author names without profile URL

fragdenstaat_de/fds_blog/templates/fds_blog/includes/social_meta.html, fragdenstaat_de/fds_cms/templates/fds_cms/social_meta.html, fragdenstaat_de/fds_events/templates/fds_events/event_detail.html, fragdenstaat_de/settings/base.py, fragdenstaat_de/templates/account/profile.html, fragdenstaat_de/templates/filingcabinet/document_detail.html, fragdenstaat_de/templates/foirequest/show.html
Reverts okfde/fragdenstaat_de#795, we don't want to deploy that right now.
=> Revert #795

README.md, devsetup.sh
- Refactor frontend() function to check for existing global links
- prevents the 'Symlink path is the same as target path' error
- Update README with Python version range and new uv dependency
- Add npm as required dependency for exif postscript
=> 🐛 fix devsetup: prevent duplicate pnpm global linking

pyproject.toml, requirements-dev.txt
this time including pyproject.toml
cf. f392139
=> remove Sphinx again

pnpm-lock.yaml, requirements-dev.txt, requirements-production.txt, requirements.txt
https://github.com/okfde/froide/pull/1126
=> postupload tabclose fix-ups for removeEventListener
